import argparse
import asyncio
import json
import logging
import os
import threading
from http.server import HTTPServer, SimpleHTTPRequestHandler

import websockets

from qa_agent.config import Settings
from qa_agent.llm import preflight_llm
from qa_agent.runner import CrawlRunner
from qa_agent.workflow_recorder import record_workflow_session

ACTIVE_SETTINGS: Settings | None = None

SITE_PROFILE_ENV_KEYS = (
    "QA_SITE_CONFIG_FILE",
    "QA_BASE_URL",
    "QA_SITE_NAME",
    "QA_START_PATH",
    "QA_DISCOVERY_SEED_ROUTES",
    "QA_PUBLIC_ROUTES",
    "QA_LOGIN_URL",
    "QA_LOGIN_PATHS",
    "QA_AUTH_EMAIL_SELECTORS",
    "QA_AUTH_PASSWORD_SELECTORS",
    "QA_AUTH_SUBMIT_SELECTORS",
    "QA_AUTH_SUCCESS_PATHS",
    "QA_AUTH_BLOCKING_PATHS",
    "QA_SESSION_FILE",
    "QA_STATE_FILE",
    "QA_LOG_FILE",
    "QA_REPORT_FILE",
    "QA_HISTORY_FILE",
    "QA_SCREENSHOT_DIR",
    "QA_WORKFLOWS_FILE",
    "QA_KNOWLEDGE_FILE",
    "QA_LLM_DEBUG_FILE",
    "QA_SIDECAR_FILE",
)


def _write_sidecar(
    state_file: str = "crawl_state.json",
    history_file: str = "history.json",
    knowledge_file: str = "qa_knowledge.json",
    workspace: dict | None = None,
    sidecar_file: str = "qa_data.js",
) -> None:
    """Write qa_data.js — a JS sidecar that embeds crawl state so
    dashboard.html works when opened directly as file:// in a browser."""
    import json, os
    state, history, knowledge = {}, [], {}
    if os.path.exists(state_file):
        try:
            with open(state_file, encoding="utf-8") as f:
                state = json.load(f)
        except Exception:
            pass
    if os.path.exists(history_file):
        try:
            with open(history_file, encoding="utf-8") as f:
                history = json.load(f)
        except Exception:
            pass
    if os.path.exists(knowledge_file):
        try:
            with open(knowledge_file, encoding="utf-8") as f:
                knowledge = json.load(f)
        except Exception:
            pass

    # Build lean pages list — strip heavy fields to keep file size reasonable
    lean_pages = [
        {
            "url":          p.get("url", ""),
            "title":        p.get("title", ""),
            "crawl_phase":  p.get("crawl_phase", "authenticated"),
            "http_status":  p.get("http_status", 0),
            "load_time_ms": p.get("load_time_ms", 0),
            "links_found":  p.get("links_found", 0),
            "api_failures": p.get("api_failures", 0),
            "perf_metrics": p.get("perf_metrics", {}),
            "analysis":     p.get("analysis", {}),
            "interaction_results": p.get("interaction_results", [])[:80],
            "root_state": p.get("root_state", {}),
            "discovered_links": p.get("discovered_links", [])[:40],
            "states_seen": p.get("states_seen", 0),
            "state_transitions": p.get("state_transitions", 0),
        }
        for p in state.get("pages_data", [])[:300]
    ]

    sidecar = {
        "pages_data":          lean_pages,
        "coverage":            state.get("coverage", {}),
        "interaction_records": state.get("interaction_records", {}),
        "workflow_results":    state.get("workflow_results", []),
        "state_graph":         state.get("state_graph", {}),
        "workspace":           workspace or {},
    }

    js = (
        "// Auto-generated by agent.py — do not edit manually.\n"
        "// Loaded by dashboard.html so it works without a running server.\n"
        f"window.__QA_STATE__   = {json.dumps(sidecar, default=str)};\n"
        f"window.__QA_HISTORY__ = {json.dumps(history, default=str)};\n"
        f"window.__QA_KNOWLEDGE__ = {json.dumps(knowledge, default=str)};\n"
    )
    with open(sidecar_file, "w", encoding="utf-8") as f:
        f.write(js)
    size_kb = round(len(js) / 1024, 1)
    print(f"  Sidecar  : {sidecar_file} written ({size_kb} KB) — open dashboard.html directly in browser")


def _load_dotenv(path: str = ".env") -> None:
    """Minimal .env loader — no dependency on python-dotenv."""
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val


_load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))

ws_clients: set = set()


def _warn_env_aliases() -> None:
    alias_rows = [
        ("MAX_PAGES", "QA_MAX_PAGES"),
        ("RETRY_THRESHOLD", "QA_RETRY_THRESHOLD"),
        ("SLACK_WEBHOOK", "QA_SLACK_WEBHOOK"),
    ]
    warned = False
    for wrong_key, correct_key in alias_rows:
        if os.getenv(wrong_key) and not os.getenv(correct_key):
            if not warned:
                print("\n  NOTE: Found legacy or unsupported env keys.")
                warned = True
            print(f"  {wrong_key} is ignored; use {correct_key} instead.")


def _normalize_site_id(value: str) -> str:
    raw = (value or "").strip().lower()
    normalized = []
    last_was_sep = False
    for ch in raw:
        if ch.isalnum():
            normalized.append(ch)
            last_was_sep = False
            continue
        if not last_was_sep:
            normalized.append("-")
            last_was_sep = True
    return "".join(normalized).strip("-")


def _prepare_site_selection(site_id: str) -> None:
    requested_site_id = _normalize_site_id(site_id)
    current_site_id = _normalize_site_id(os.getenv("QA_SITE_ID", ""))
    if current_site_id and requested_site_id and current_site_id != requested_site_id:
        for key in SITE_PROFILE_ENV_KEYS:
            os.environ.pop(key, None)
    if requested_site_id:
        os.environ["QA_SITE_ID"] = requested_site_id


def _quiet_ws_logger() -> logging.Logger:
    logger = logging.getLogger("qa_agent.websocket")
    logger.handlers.clear()
    logger.addHandler(logging.NullHandler())
    logger.propagate = False
    logger.setLevel(logging.CRITICAL)
    return logger


async def broadcast(msg: dict) -> None:
    if not ws_clients:
        return
    payload = json.dumps(msg, default=str)
    await asyncio.gather(*(c.send(payload) for c in list(ws_clients)), return_exceptions=True)


async def ws_handler(websocket):
    ws_clients.add(websocket)
    try:
        state_file = ACTIVE_SETTINGS.state_file if ACTIVE_SETTINGS else "crawl_state.json"
        if os.path.exists(state_file):
            with open(state_file, encoding="utf-8") as f:
                state_data = json.load(f)
            pages = state_data.get("pages_data", [])
            if pages:
                lean_pages = [
                    {
                        "url": p.get("url", ""),
                        "title": p.get("title", ""),
                        "crawl_phase": p.get("crawl_phase", "authenticated"),
                        "http_status": p.get("http_status", 0),
                        "load_time_ms": p.get("load_time_ms", 0),
                        "links_found": p.get("links_found", 0),
                        "api_failures": p.get("api_failures", 0),
                        "perf_metrics": p.get("perf_metrics", {}),
                        "analysis": p.get("analysis", {}),
                        "interaction_results": p.get("interaction_results", [])[:80],
                        "root_state": p.get("root_state", {}),
                        "discovered_links": p.get("discovered_links", [])[:40],
                        "states_seen": p.get("states_seen", 0),
                        "state_transitions": p.get("state_transitions", 0),
                    }
                    for p in pages[:300]
                ]
                await websocket.send(json.dumps({
                    "type": "init",
                    "pages": lean_pages,
                    "coverage": state_data.get("coverage", {}),
                    "interaction_records": state_data.get("interaction_records", {}),
                    "workflow_results": state_data.get("workflow_results", []),
                    "state_graph": state_data.get("state_graph", {}),
                    "workspace": ACTIVE_SETTINGS.workspace_info if ACTIVE_SETTINGS else {},
                }, default=str))
    except Exception:
        pass
    try:
        await websocket.wait_closed()
    finally:
        ws_clients.discard(websocket)


async def main() -> None:
    parser = argparse.ArgumentParser(description="Open Web QA Agent")
    parser.add_argument("--resume", action="store_true", help="Resume from the current site state file")
    parser.add_argument(
        "--record-workflow",
        action="store_true",
        help="Open a guided browser session and save a workflow to the current site workflow file",
    )
    parser.add_argument(
        "--workflow-name",
        default="",
        help="Optional workflow name to use with --record-workflow",
    )
    parser.add_argument(
        "--site",
        default="",
        help="Optional site profile id under sites/<site_id>",
    )
    args = parser.parse_args()

    if args.site:
        _prepare_site_selection(args.site)
    settings = Settings.from_env()
    global ACTIVE_SETTINGS
    ACTIVE_SETTINGS = settings
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    if args.record_workflow:
        print(f"\n{'='*55}")
        print("  Workflow Recorder")
        print(f"{'='*55}")
        print(f"  Target URL : {settings.base_url}")
        print(f"  Workflows  : {settings.workflows_file}")
        print(f"{'='*55}\n")
        try:
            result = await record_workflow_session(settings, workflow_name=args.workflow_name)
            action = "Updated" if result["replaced"] else "Saved"
            print(
                f"\n  {action} workflow '{result['name']}' "
                f"with {result['steps']} step(s)"
            )
            print(f"  Route     : {result['route']}")
            print(f"  Start URL : {result['start_url']}")
            print(f"  File      : {result['workflows_file']}")
        except RuntimeError as e:
            print(f"\n  ERROR: {e}")
        return

    # ── Startup diagnostics ──────────────────────────────────────────────
    print(f"\n{'='*55}")
    print(f"  Open Web QA Agent")
    print(f"{'='*55}")
    print(f"  Site       : {settings.site_name} ({settings.site_id})")
    print(f"  Target URL : {settings.base_url}")
    print(f"  Email      : {settings.email or '(not set)'}")
    print(f"  LLM        : {settings.llm_provider}/{settings.llm_model} @ {settings.llm_url}")
    print(f"  Max pages  : {settings.max_pages}")
    print(f"  Scenarios  : {'on' if settings.run_scenarios else 'off'}")
    print(f"  Site dir   : {settings.site_dir}")
    print(f"  Workflows  : {settings.workflows_file}")
    print(f"  Resume     : {'yes' if args.resume else 'no'}")
    print(f"{'='*55}")

    llm_ok, llm_detail = await asyncio.to_thread(preflight_llm, settings)
    if settings.llm_preflight:
        if llm_ok:
            print(f"  LLM check  : OK ({llm_detail})")
        else:
            print(f"  WARNING: LLM preflight failed")
            print(f"  Reason     : {llm_detail}")
            print(f"  Log file   : {settings.llm_debug_file}")
            print("  Analysis will use fallback heuristics until this is fixed.")
            if settings.llm_fail_fast:
                raise RuntimeError(
                    f"LLM preflight failed and QA_LLM_FAIL_FAST=1: {llm_detail}\n"
                    f"See {settings.llm_debug_file} for details."
                )
    else:
        print("  LLM check  : skipped")

    if not settings.email or not settings.password:
        print("\n  WARNING: QA_EMAIL or QA_PASSWORD not set.")
        print("  Create .env in the project root and fill in your credentials.\n")

    _warn_env_aliases()

    if settings.base_url == "https://example.com":
        print("\n  NOTE: Using default QA_BASE_URL=https://example.com")
        print("  Set QA_BASE_URL or create a site profile under sites/<site_id>/site.json\n")

    class QuietHandler(SimpleHTTPRequestHandler):
        def do_GET(self):
            if self.path in ("/api/state", "/api/state/"):
                target = ACTIVE_SETTINGS.state_file if ACTIVE_SETTINGS else "crawl_state.json"
                if not os.path.exists(target):
                    self.send_response(404)
                    self.end_headers()
                    self.wfile.write(b'{"error":"not found"}')
                    return
                with open(target, "rb") as f:
                    payload = f.read()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(payload)
                return
            if self.path in ("/api/history", "/api/history/"):
                target = ACTIVE_SETTINGS.history_file if ACTIVE_SETTINGS else "history.json"
                if not os.path.exists(target):
                    self.send_response(404)
                    self.end_headers()
                    self.wfile.write(b'{"error":"not found"}')
                    return
                with open(target, "rb") as f:
                    payload = f.read()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(payload)
                return
            if self.path in ("/api/knowledge", "/api/knowledge/"):
                target = ACTIVE_SETTINGS.knowledge_file if ACTIVE_SETTINGS else "qa_knowledge.json"
                if not os.path.exists(target):
                    self.send_response(404)
                    self.end_headers()
                    self.wfile.write(b'{"error":"not found"}')
                    return
                with open(target, "rb") as f:
                    payload = f.read()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(payload)
                return
            if self.path in ("/api/workspace", "/api/workspace/"):
                payload = json.dumps(ACTIVE_SETTINGS.workspace_info if ACTIVE_SETTINGS else {}, default=str).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(payload)
                return
            super().do_GET()

        def log_message(self, *args):
            pass
        def log_error(self, *args):
            pass

    httpd = HTTPServer(("localhost", settings.http_port), QuietHandler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()

    ws_server = await websockets.serve(
        ws_handler,
        "localhost",
        settings.ws_port,
        logger=_quiet_ws_logger(),
    )
    print(f"\n  Dashboard : http://localhost:{settings.http_port}/dashboard.html")
    print(f"  Workspace : http://localhost:{settings.http_port}/api/workspace")
    print(f"  WebSocket : ws://localhost:{settings.ws_port}\n")

    runner = CrawlRunner(settings, broadcast=broadcast)
    try:
        state = await runner.run(resume=args.resume)
        print(
            f"\n  Done. pages={len(state.pages_data)} "
            f"api_calls={len(state.api_log)} "
            f"workflows={len(state.workflow_results)}"
        )
        print(f"  Report : {settings.report_file}")
        print(f"  Log    : {settings.log_file}")
    except RuntimeError as e:
        print(f"\n  ERROR: {e}")
    finally:
        # Always write sidecar so dashboard.html keeps working after agent stops
        _write_sidecar(
            state_file=settings.state_file,
            history_file=settings.history_file,
            knowledge_file=settings.knowledge_file,
            workspace=settings.workspace_info,
            sidecar_file=settings.sidecar_file,
        )
        ws_server.close()
        await ws_server.wait_closed()
        print("\nDashboard still viewable at:")
        print(f"   - http://localhost:{settings.http_port}/dashboard.html  (if serve.py is running)")
        print(f"   - Open dashboard.html directly in your browser (uses {settings.sidecar_file})")
        print(f"   - Run: python serve.py --site {settings.site_id}")


if __name__ == "__main__":
    asyncio.run(main())
